services:
    - type: web
      name: health-tracker-backend
      env: node
      buildCommand: npm install
      startCommand: npm start
      envVars:
          - key: NODE_ENV
            value: production
          - key: PORT
            value: 10000
          - key: JWT_SECRET
            generateValue: true
          - key: MONGODB_URI
            sync: false
